build: use ubuntu:18.04 as a base image

diff --git a/docker/linux/x86_64/Dockerfile.ubuntu b/docker/linux/x86_64/Dockerfile.ubuntu
--- a/docker/linux/x86_64/Dockerfile.ubuntu
+++ b/docker/linux/x86_64/Dockerfile.ubuntu
@@ -3,10 +3,11 @@
 #     However, if your host (or target) machine's glibc version < 2.33, `libmediapipe_c.so` built on Arch Linux won't work on them.
 #     In suce a case, use this `Dockerfile.ubuntu` instead of `Dockerfile`.
 ARG UID=1000
+ARG ANDROID_SDK_BUILD_TOOLS_VERSION=30.0.3
 ARG ANDROID_SDK_VERSION=30
 ARG ANDROID_NDK_VERSION=21.4.7075529
 
-FROM ubuntu:20.04 AS base
+FROM ubuntu:18.04 AS base
 
 ARG UID
 
@@ -20,6 +21,8 @@ RUN apt-get update && \
         clang \
         curl \
         dirmngr \
+        gcc-8 \
+        g++-8 \
         git \
         gnupg \
         libegl1-mesa-dev \
@@ -32,28 +35,33 @@ RUN apt-get update && \
         software-properties-common \
         sudo \
         unzip \
-        zip
+        zip && \
+    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-8
+
 
 FROM base AS android
 
 WORKDIR /tmp
 
+ARG ANDROID_SDK_BUILD_TOOLS_VERSION
 ARG ANDROID_SDK_VERSION
 ARG ANDROID_NDK_VERSION
 
 ENV COMMANDLINETOOLS_ZIP commandlinetools.zip
-ENV COMMANDLINETOOLS_SHA256 87f6dcf41d4e642e37ba03cb2e387a542aa0bd73cb689a9e7152aad40a6e7a08
+ENV COMMANDLINETOOLS_SHA256 124f2d5115eee365df6cf3228ffbca6fc3911d16f8025bebd5b1c6e2fcfa7faf
 
-RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -o ${COMMANDLINETOOLS_ZIP} && \
-    (test "$(sha256sum ${COMMANDLINETOOLS_ZIP})" = "${COMMANDLINETOOLS_SHA256}  ${COMMANDLINETOOLS_ZIP}" || { echo 'Checksum Failed'; exit 1; })
-RUN unzip ${COMMANDLINETOOLS_ZIP} -d /opt/android
-RUN yes | /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --licenses
+
+RUN curl -L https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o ${COMMANDLINETOOLS_ZIP} && \
+    (test "$(sha256sum ${COMMANDLINETOOLS_ZIP})" = "${COMMANDLINETOOLS_SHA256}  ${COMMANDLINETOOLS_ZIP}" || { echo 'Checksum Failed'; exit 1; }) && \
+    unzip ${COMMANDLINETOOLS_ZIP} -d /opt/android
+
+RUN  yes | /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --licenses
 RUN /opt/android/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android --install \
-    "platforms;android-${ANDROID_SDK_VERSION}" \
-    "platform-tools" \
-    "build-tools;30.0.3" \
-    "ndk;${ANDROID_NDK_VERSION}"
-RUN rm ${COMMANDLINETOOLS_ZIP}
+        "platforms;android-${ANDROID_SDK_VERSION}" \
+        "platform-tools" \
+        "build-tools;${ANDROID_SDK_BUILD_TOOLS_VERSION}" \
+        "ndk;${ANDROID_NDK_VERSION}" && \
+    rm ${COMMANDLINETOOLS_ZIP}
 
 
 FROM base AS builder
@@ -71,13 +79,29 @@ RUN add-apt-repository -y ppa:deadsnakes/ppa && \
     python3.9 get-pip.py && \
     ln -s /usr/bin/python3.9 /usr/local/bin/python
 
-# install NuGet
+# Install NuGet
 RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
-    apt-add-repository -y 'deb https://download.mono-project.com/repo/ubuntu stable-focal main' && \
-    apt-get install -y --no-install-recommends mono-complete && \
+    apt-add-repository -y 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main'
+
+####
+# NOTE
+#   At the moment (2021.12), very unstable in some country (https://github.com/mono/mono/issues/21273).
+#
+#   If you encounter 504 Timeout errors, insert RUN commands as follows and install those *.deb files forcefully (note `; exit 0` at the end).
+#
+#   # if failing to download libmono-system-reactive-providers2.2-cil_6.12.0.122-0xamarin1+ubuntu1804b1_all.deb...
+#   RUN curl -X GET https://download.mono-project.com/repo/ubuntu/pool/main/m/mono/libmono-system-reactive-providers2.2-cil_6.12.0.122-0xamarin1+ubuntu1804b1_all.deb -o libmono-system-reactive-providers2.2-cil_6.12.0.122-0xamarin1+ubuntu1804b1_all.deb && \
+#       dpkg -i libmono-system-reactive-providers2.2-cil_6.12.0.122-0xamarin1+ubuntu1804b1_all.deb ; exit 0
+#
+#   # Repeat if failing to download other files
+#   # RUN curl -X GET ... -o ... ; exit 0
+#
+#   RUN apt --fix-broken install -y
+
+RUN apt-get install -y --no-install-recommends mono-complete && \
     curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe && \
-    bash -c 'echo -e "#!/bin/bash\nmono /usr/local/bin/nuget.exe \$@" | sudo tee -a /usr/local/bin/nuget' && \
-    sudo chmod +x /usr/local/bin/nuget
+    bash -c 'echo -e "#!/bin/bash\nmono /usr/local/bin/nuget.exe \$@" | tee -a /usr/local/bin/nuget' && \
+    chmod +x /usr/local/bin/nuget
 
 # install Bazelisk
 RUN apt-get install -y --no-install-recommends npm && \
@@ -118,7 +142,7 @@ RUN git clone https://git.ffmpeg.org/ffmpeg.git && \
         --disable-vaapi \
         --disable-vdpau \
         --disable-videotoolbox && \
-    make -j `nproc` && \
+    make -j "$(nproc)" && \
     make install && \
     cd .. && \
     rm -rf ffmpeg
@@ -133,12 +157,8 @@ WORKDIR /home/mediapipe
 ENV NPM_PREFIX /home/mediapipe/.npm-packages
 ENV PATH ${NPM_PREFIX}/bin:/home/mediapipe/.local/bin:${PATH}
 
-# install Bazelisk
-RUN bash -c 'echo -e "prefix = ${NPM_PREFIX}\n" > /home/mediapipe/.npmrc' && \
-    npm install -g @bazel/bazelisk
-
 # install numpy
-RUN pip install --user numpy
+RUN pip install --no-cache-dir --user numpy
 
 
 FROM builder
@@ -149,11 +169,11 @@ ENV ANDROID_HOME /opt/android
 ENV ANDROID_NDK_HOME /opt/android/ndk/${ANDROID_NDK_VERSION}
 ENV PYTHON_BIN_PATH /usr/bin/python3.9
 
-ADD .bazelrc .
-ADD packages.config .
-ADD build.py .
-ADD WORKSPACE .
-ADD mediapipe_api mediapipe_api
-ADD third_party third_party
+COPY .bazelrc .
+COPY packages.config .
+COPY build.py .
+COPY WORKSPACE .
+COPY mediapipe_api mediapipe_api
+COPY third_party third_party
 
 CMD ["/bin/bash"]
